### ISSUE TITLE
unable to set max_connections parameter

### ISSUE THREAD

**Issue by vasudba** [agroal/pgagroal#100]
unable to set max_connections parameter getting error below while starting pgagroal with max_connections=2000.
pgagroal: max_connections is larger than the number of available file descriptors for connections (994)

**Comment by jesperpedersen** [comment]
You only have 994 file descriptors available to the process after pgagroal has used its file descriptors -- see `ulimit -aH`.

Either raise it or use a lower number of connections.

**Comment by vasudba** [comment]
Hi,

Below are ulimit settings.

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31500
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Also i am installed pgagroal inside docker container.

**Comment by jesperpedersen** [comment]
Is that the host machine or the docker container ?

**Comment by vasudba** [comment]
it is docker container

**Comment by jesperpedersen** [comment]
And the ulimit output from the host ?

**Comment by vasudba** [comment]
No, it is inside docker container

**Comment by jesperpedersen** [comment]
Yeah, but is the output from the host machine where the docker container is going to run ?

**Comment by vasudba** [comment]
But looks like output from both host machine and docker container are different.

Host machine
==============
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31500
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31500
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Docker container
=====================
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31500
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by jesperpedersen** [comment]
Ah, try with `ulimit -a` instead - that should show the soft limit.

**Comment by vasudba** [comment]
host machine:
----------------------------
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31500
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31500
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Docker container
------------------------------
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31500
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by jesperpedersen** [comment]
Yeah, so the host machine is restricting to 1024 file descriptors, and pgagroal reserves 30 giving you 994 for connections.

However, why do you need 2000 connections ? Can the PostgreSQL instance support that many ? Using a connection pool like pgagroal should limit the need for opening many connections towards PostgreSQL in the first place.

If you really need that many you will need to raise the soft file descriptor limit to tell pgagroal that you are sure about that decision.

**Comment by vasudba** [comment]
Hi,

Thank you for help, After changed soft limit, able to start pgagroal.
