### ISSUE TITLE
pass-throuh security risks

### ISSUE THREAD

**Issue by mrechte** [agroal/pgagroal#101]
Regarding security as pass-throuh mode, it is mentioned: 
> Note, that this can lead to replay attacks based on the network setup

Could you elaborate please ?

**Comment by jesperpedersen** [comment]
It is because the hash doesn't change - I'll expand on it in the documentation.

Ideally either a user vault or authentication query should be used instead.

**Comment by jesperpedersen** [comment]
Done.

Thanks for your feedback !

**Comment by mrechte** [comment]
Thanks a lot for your prompt feed backs.

Best regards.

Le 16/09/2020 à 16:22, Jesper Pedersen a écrit :
