### ISSUE TITLE
Can pgagroal listen on a UNIX socket ?

### ISSUE THREAD

**Issue by mrechte** [agroal/pgagroal#102]
Can a sql client connect to pgagroal using a UNIX socket rather than a tcp socket ?
Thanks

**Comment by jesperpedersen** [comment]
Not yet - what is your use case ?

The Unix Domain Sockets infrastructure in #40 would make it possible though.

**Comment by jesperpedersen** [comment]
I have added support for this, so now you can do

```
psql -h /tmp -p 2345 -U myuser mydb
```

Thanks for the suggestion !
