### ISSUE TITLE
pgagroal_databases.conf does not support max_size = 0

### ISSUE THREAD

**Issue by mrechte** [agroal/pgagroal#106]
Trying to disable access to postgres database through the pooler I inserted:
`postgres   all      0` in pgagroal_databases.conf
However I can still connect to postgres.

**Comment by jesperpedersen** [comment]
You need in `pgagroal_hba.conf`

```
host postgres all all reject
```

instead.

But I see where you are coming from, so I'll enhance the limit checks during startup.

**Comment by jesperpedersen** [comment]
I have enhanced the checks.

Thanks for the feedback !
