### ISSUE TITLE
Support reload conf without restarting

### ISSUE THREAD

**Issue by mrechte** [agroal/pgagroal#107]
I would like the ability to reload the conf without having to restart the service:

```
# systemctl reload pgagroal
Failed to reload pgagroal.service: Job type reload is not applicable for unit pgagroal.service.
```

**Comment by jesperpedersen** [comment]
Which configuration settings are you most interested in ? Or just in general ?

**Comment by davidfetter** [comment]
I don't know about @mrechte, but from what I've seen, the more things you can do with a `SIGHUP` (or whatever similar thing you do to reload configuration without restarting) the better.

**Comment by jesperpedersen** [comment]
All the easy ones are supported now. The remaining ones will be on a case-by-case basis, so closing.

Thanks !
