### ISSUE TITLE
pgagroal-cli segfaults

### ISSUE THREAD

**Issue by devrimgunduz-edb** [agroal/pgagroal#112]
Hi,
pgagroal-cli (0.9.0) segfaults on Fedora 32. Can you please take a look?

- PostgreSQL 12
- pgagroal 0.9.0
- trust auth in pgagroal's hba

$ pgagroal-cli  -c /etc/pgagroal/pgagroal.conf  -h localhost -p 2345 -U postgres -P postgres status
Status:              Running
Active connections:  0
Total connections:   0
Max connections:     100
munmap_chunk(): invalid pointer
Aborted (core dumped)

**Comment by jesperpedersen** [comment]
YES ! Lets use all the options :)

Thanks Devrim !
