### ISSUE TITLE
Fail to get new connections

### ISSUE THREAD

**Issue by yaroot** [agroal/pgagroal#115]
This is a follow up for https://github.com/agroal/pgagroal/issues/110

Client would throw this error and not be able to connect through pgagroal

`pg8000.exceptions.ProgrammingError: {'S': 'FATAL', 'V': 'FATAL', 'C': '53300', 'M': 'connection pool is full'}`

**Comment by yaroot** [comment]
[pgagroal.log.gz](https://github.com/agroal/pgagroal/files/5375004/pgagroal.log.gz)

![Screenshot_2020-10-14T10:21:36+09:00](https://user-images.githubusercontent.com/42634/95932757-3a6a7480-0dbc-11eb-8ffb-3320b2e1500b.png)

Metrics are in UTC, logs are in UTC+9:00

**Comment by jesperpedersen** [comment]
Thanks for the trace !

However, it shows that it is maxes out on 70 connections so the error is correct if you used the configuration in #110. Could you do another run and keep an eye on `/methics` ?

Also, if there is a problem check the output from `ps aux | grep pgagroal` ? The `pgagroal_active_connections` should be in line with the actual connections...

Do you have a test case that I can use locally ?

**Comment by yaroot** [comment]
The problem is that it stays at 70 after terminating the clients. I've been using the code posted in #100

**Comment by jesperpedersen** [comment]
This is very helpful, thank you !

Although you are missing a `conn.rollback()` and a `conn.close()` I can replicate the issue you are seeing when doing the `^C` testing.

**Comment by jesperpedersen** [comment]
I have pushed a fix to `master` and `0.9.x` - if would be great if you could do a rerun of all your test cases.

The main issue is that the clients doesn't know about the cached connections since there is no prefill in play. I'll think some more about that scenario...

**Comment by yaroot** [comment]
I rerun the test on 5e01f52eebc9e84a9f58ef1bc9a92f8862cb37d8 for a few hour, nothing happened so far, still trying to trigger `connection pool is full`, usually the scala code would do the trick.

I've added `.rollback()` on exception (the code didn't even reach this branch since the last few commits), the connection will be closed by the `with` construction.

**Comment by jesperpedersen** [comment]
ok, sounds good. My tests with your clients are successful now.

**Comment by yaroot** [comment]
Closing as there's nothing more I could find, it's a pleasure to work with you.
