### ISSUE TITLE
Offer binary distributions (e.g. Docker or ppa/deb)

### ISSUE THREAD

**Issue by dfex55** [agroal/pgagroal#116]
To help distribution and popularity gain, it would be helpful to have usage-ready binary distributions. People can evaluate and decide much faster.

My preferable solution would be a docker image, published on docker hub with the latest release.

**Comment by jesperpedersen** [comment]
I understand where you are coming from but providing a community binary distribution is outside of the scope of the project since one of the main points of the projects is the pooling aspect. Enabling pooling requires defined users and these are specific to each deployment.

That being said, there are binaries for various platforms (`yum.postgresql.org` and OpenSuSE):

```
https://agroal.github.io/pgagroal/releases.html
```

and an issue has been filed for `apt.postgresql.org` (Debian and Ubuntu) as well

```
https://redmine.postgresql.org/issues/5566
```

Hope this provide some insight.

**Comment by sebastianwebber** [comment]
> I understand where you are coming from but providing a community binary distribution is outside of the scope of the project since one of the main points of the projects is the pooling aspect. Enabling pooling requires defined users and these are specific to each deployment.

so the project will not provide an official image?
I could not find any at docker hub: https://hub.docker.com/search?q=pgagroal&type=image

**Comment by jesperpedersen** [comment]
It is more of a matter of how that distribution would look and interact with an external PostgreSQL instance.

If there is just a binary image using the RPMs (assuming CentOS 8 / yum.postgresql.org) then pgagroal would be running in pass-through security mode which has issues if deployed on an external network. See https://agroal.github.io/pgagroal/security.html.

However, if somebody can make a solid design where user vaults can be used, and a plan for network security concerns then I have no issues deploying an image on https://quay.io/.

**Comment by jesperpedersen** [comment]
Which that being said, I do have plans to look into this area - others may have a different timeline than me though

**Comment by sebastianwebber** [comment]
> It is more of a matter of how that distribution would look and interact with an external PostgreSQL instance.

That isn't true when we are talking about containers.

> If there is just a binary image using the RPMs (assuming CentOS 8 / yum.postgresql.org) then pgagroal would be running in pass-through security mode which has issues if deployed on an external network. See https://agroal.github.io/pgagroal/security.html.
> 
> However, if somebody can make a solid design where user vaults can be used, and a plan for network security concerns then I have no issues deploying an image on https://quay.io/.

I will check that and make a proposal. I think that we can get a viable solution to get an official image.

**Comment by jesperpedersen** [comment]
Sounds good - looking forward to it !

**Comment by jesperpedersen** [comment]
BTW, feel free to start from https://github.com/jesperpedersen/podman-pgsql/tree/master/pgsql12-pgagroal-centos8 ...
