### ISSUE TITLE
Multiple instance configuration

### ISSUE THREAD

**Issue by huseynsnmz** [agroal/pgagroal#118]
Hi, I am trying to configure one pgagroal instance for multiple project. For example,

Application A --> pgagroal --> Host X
Application B --> pgagroal --> Host Y

Is it possible to use one pgagroal instance for multiple database servers?

**Comment by jesperpedersen** [comment]
pgagroal currently assumes that each server defined has the same databases with the same users.

Deploying multiple instances of pgagroal should have minimal run-time overhead, but lets try and hash out the use-case in more details if needed.

**Comment by jesperpedersen** [comment]
BTW, `Debug` message will show the size of the configuration during startup so you can check if it will fit in L1/L2/L3 CPU cache.

**Comment by huseynsnmz** [comment]
Actually, I am thinking of cost and maintenance to deploy many instances in different machines. Use cases,

1) If I have many databases for different projects with low connections, deploying many pgagroal instance can be costly. Of course there will be question that "Do we need a connection pooler?" but...
2) If we have sharding in application level to store data in many databases , we can have different databases instances. So we need to have pgagroal instance as many as database instance. As database level sharding (for example Citus), we can create a use case for failover on workers or coordinator.

I don't know maybe it is not worth it but I would love to hear your thoughts.

**Comment by jesperpedersen** [comment]
```
1. If I have many databases for different projects with low connections, deploying many pgagroal instance can be costly. Of course there will be question that "Do we need a connection pooler?" but...
````

I think doing a `--limit` configuration will serve that. Adding a connection pool will always have an overhead, but having a central connection point may have a benefit.

I think the main point for this issue having a pool going out to multiple different servers with different databases/users on them...

```
2. If we have sharding in application level to store data in many databases , we can have different databases instances. So we need to have pgagroal instance as many as database instance. As database level sharding (for example Citus), we can create a use case for failover on workers or coordinator.
```

Are you thinking that adding a `database` tag (which can be multiple) to the server section definition is the best way forward ?

When I think of shards I think of a single access point to the entire data model... no matter the database name. Can you provide a sample configuration on how you see it working ?

**Comment by huseynsnmz** [comment]
I think pgagroal_databases.conf has perfect place for it but as like you said, users can be a problem.

Example configuration,
```
pgagroal.conf

[pgagroal]
host = *
port = 2345

log_type = file
log_level = info
log_path = /tmp/pgagroal.log

max_connections = 100
idle_timeout = 600
validation = off
unix_socket_dir = /tmp/.s.pgagroal

[server01]
host = 10.10.10.5
port = 5432

[server02]
host = 10.10.10.6
port = 5432
```
```
pgagrol_databases.conf

#
# DATABASE USER MAX_SIZE INITIAL_SIZE MIN_SIZE SERVER_NAME
#
db01 all all x x server01
db02 all all x x server02
```

**Comment by changchichung** [comment]
I have trouble to find documents to explain how to add multiple psql nodes in configuration and how it works .

let's said I have three psql DB  ps01 , ps02 , ps03 all these 3 db nodes have the same DB/user/password , and one node for pgagroal (pga01) .
my questions were
1. should I config postgresql replication in ps01/ps02/ps03 first ?
2. what's the correct syntax to add multiple psql nodes in pgagroal.conf ?
something like this ?
```
[ps01]
host: 1.1.1.1
port: 5432
[ps02]
host: 2.2.2.2
port: 5432
```
3. Do I have to assign a node as primary node ? and what's the different between primary/slave nodes ?
4. after doing some upsert/delete in database , are these nodes still have the same data ?

**Comment by jesperpedersen** [comment]
@changchichung 

For 1) pgagroal doesn't do replication, so you need to set that up in PostgreSQL first - f.ex. streaming
For 2) Yes, that is the format - then pgagroal can handle failover through the provided script
For 3) pgagroal will try and find the primary in order
For 4) The PostgreSQL cluster will replicate all data

Please, use https://github.com/agroal/pgagroal/discussions for questions in the future.

For now, I'll close this issue since the feature still needs to be discussed or a design needs to be presented as I don't think the `pgagroal_databases.conf` route is optimal.
