### ISSUE TITLE
Can't build 1.0.1 on Ubuntu: Unknown CMake command "add_link_options"

### ISSUE THREAD

**Issue by dtseiler** [agroal/pgagroal#119]
I could build 1.0.0 fine on Ubuntu 18.04. But 1.0.1 throws the error about `add_link_options`:

```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
-- The C compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- pgagroal 1.0.1
-- Build type is Release
-- Performing Test COMPILER_SUPPORTS_C17
-- Performing Test COMPILER_SUPPORTS_C17 - Success
-- Found Libev: /usr/lib/x86_64-linux-gnu/libev.so (found suitable version "4.22", minimum required is "4.11")
-- libev found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- OpenSSL found
-- Found Rst2man: /usr/bin/rst2man (found version "0.14,")
-- rst2man found
-- Found Systemd: /lib/x86_64-linux-gnu/libsystemd.so
-- systemd found
CMake Error at src/CMakeLists.txt:38 (add_link_options):
  Unknown CMake command "add_link_options".

$ cmake --version
cmake version 3.10.2

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

**Comment by dtseiler** [comment]
Out of curiosity I tried to build on Ubuntu 20.04 but that has errors with libssl-dev requiring an older version of libssl than what was already installed. Not going to dig into that just yet.

**Comment by dtseiler** [comment]
It looks like `add_link_options` was [added in cmake 3.13](https://cmake.org/cmake/help/latest/command/add_link_options.html#command:add_link_options). Ubuntu 18.04 repo only has cmake 3.10.

**Comment by dtseiler** [comment]
FWIW, Ubuntu 20.04 uses cmake 3.16 and the cmake step works there. There appears to be some other issues though unrelated to this.

However I'd really need it to work on Ubuntu 18.04. We aren't planning to move to 20.04 any time soon due to 20.04 using the newer glibc that has the [notorious collation change from glibc 2.28](https://postgresql.verite.pro/blog/2018/08/27/glibc-upgrade.html).

**Comment by dtseiler** [comment]
As you probably guessed this is basically from the one change for the 1.0.1 release: https://github.com/agroal/pgagroal/commit/e646f2221842082588296f6db938702a4fbf1b8b

**Comment by dtseiler** [comment]
Looks like RHEL/CentOS 8 only has cmake 3.11, so this would likely be broken there as well?

**Comment by jesperpedersen** [comment]
Our lab is being moved atm, but I have pushed a fix that should work.

Thanks Don !

**Comment by dtseiler** [comment]
Just an FYI that I was able to successfully build from your master branch on ubuntu 18.04. Thanks!
