### ISSUE TITLE
Build Question: Does pgagroal need postgresql-client installed?

### ISSUE THREAD

**Issue by dtseiler** [agroal/pgagroal#126]
In the absence of a PGDG Ubuntu/apt/deb package, I'm looking at setting up an internal build. We would want to run pgagroal on its own server separate of the DB (like we currently do with pgbouncer).

What postgresql packages need to be installed to build pgagroal? postgresql-client? just libpq5 perhaps?

**Comment by jesperpedersen** [comment]
No PostgreSQL packages are needed; use your build platform with the required dependencies. I hope that a PGDB package will be available in the future, but I'm not able to make that happen. 

You can use https://github.com/agroal/pgagroal/discussions in the future for questions.

**Comment by huseynsnmz** [comment]
Hello,

Sorry for writing on the closed issue but I wanted to say there is already a pgagroal package in PGDG repositories:
https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8-x86_64/pgagroal-1.0.2-1.rhel8.x86_64.rpm

 It is one version behind but packager is updating packages very quickly. Here is the redmine page for bug report etc.:
https://redmine.postgresql.org/projects/pgrpms

**Comment by jesperpedersen** [comment]
There is https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8-x86_64/pgagroal-1.1.0-1.rhel8.x86_64.rpm as well

**Comment by dtseiler** [comment]
@huseynsnmz I'm afraid I need an Ubuntu package. We have a redmine issue already created for this at https://redmine.postgresql.org/issues/5566
