### ISSUE TITLE
Can't set initial or max size in limits file

### ISSUE THREAD

**Issue by dtseiler** [agroal/pgagroal#129]
**Describe the bug**

When I create a pgagroal_databases.conf and set values for initial and max size, pgagroal fails to start and the log has this error:

```
FATAL configuration.c:1293 Unknown user 'all' for limit entry 0
```

If I don't use the limits file, or if I just take the limits out so the contents are `all all all` per the example at https://github.com/agroal/pgagroal/blob/master/doc/CONFIGURATION.md#pgagroal_databases-configuration, it starts just fine.

**To Reproduce**

Create /usr/local/etc/pgagroal/pgagroal_databases.conf with these contents (tab delimited fields):

```
#
# DATABASE USER  MAX_SIZE INITIAL_SIZE MIN_SIZE
#
all     all     all     50      25
```

Start pgagroal like so:

```
$ sudo -u pgagroal /usr/local/bin/pgagroal -d -c /usr/local/etc/pgagroal/pgagroal.conf -a /usr/local/etc/pgagroal/pgagroal_hba.conf -l /usr/local/etc/pgagroal/pgagroal_databases.conf
```

**Version**

1.1.0

**Comment by jesperpedersen** [comment]
The limits functionality needs more work for corner-cases like this. Maybe `all` should be a reserved word for `max_size`.

For now, you can set the limits for the specific users that you have like

```
username database all max initial min
```

**Comment by jesperpedersen** [comment]
I have updated the way limits are parsed, so new docs. I think it works better this way, but not going to back patch to 1.1.x.

Thanks for the feedback Don !
