### ISSUE TITLE
Package for Debian based distributions

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#133]
See

 https://redmine.postgresql.org/issues/5566

**Comment by df7cb** [comment]
I found the time to package it, packages are on the way to Debian and apt.postgresql.org.

**Comment by jesperpedersen** [comment]
@df7cb Thanks !

**Comment by jesperpedersen** [comment]
I added it to https://agroal.github.io/pgagroal/releases.html

**Comment by df7cb** [comment]
(I can't close this issue even when it's assigned to me.)

**Comment by jesperpedersen** [comment]
I have to look into that - but lets leave it open until we have your PR in
