### ISSUE TITLE
Please clarify max_connections, MAX_SIZE parameter usage

### ISSUE THREAD

**Issue by mrechte** [agroal/pgagroal#135]
I am completely lost with theses parameters usage.
In pgagroal.conf, max_connections is the limit of total number of connections from client -> pgagroal ?
In pgagroal_database.conf, MAX_SIZE is the limit for client  -> pgagroal (for a given user/database) ?
How do I control the number of connections from pgagroal -> PG server ?
Does one pgagroal instance manages one pool, or can I have several  ?
Thanks for clarifications

**Comment by jesperpedersen** [comment]
All numbers are from pgagroal to PostgreSQL.

There are currently no settings for clients other than `blocking_timeout` (and `disconnect_client`).

So, you sub divide your `max_connections` to each database using the `pgagroal_databases.conf` file.

You can use https://github.com/agroal/pgagroal/discussions for questions.

Thanks !
