### ISSUE TITLE
Add more client metrics

### ISSUE THREAD

**Issue by An-DJ** [agroal/pgagroal#158]
**Is your feature request related to a problem? Please describe.**
There is a lack of metrics to characterize the client state.

**Describe the solution you'd like**

- [X] Add `pgagroal_client_active` which characterizes the number of active clients #157 
- [X] Add `pgagroal_client_wait` which characterizes the number of waiting clients #157 
- [ ] Add per-db statistics to the metrics above

**Comment by jesperpedersen** [comment]
Maybe this is more related to #105

**Comment by jesperpedersen** [comment]
Completed tasks for GSoC 2021
