### ISSUE TITLE
Add more pool metrics

### ISSUE THREAD

**Issue by An-DJ** [agroal/pgagroal#159]
**Is your feature request related to a problem? Please describe.**
There is a lack of metrics to characterize the pool state.

**Describe the solution you'd like**

- [X] Add `pgagroal_query_count` which characterizes the number of queries in the most recent time interval.
- [X] Add `pgagroal_tx_count` which characterizes the number of transactions in the most recent time interval.
- [X] Add `pgagroal_wait_time` which characterizes the previous client waiting time.

**Comment by jesperpedersen** [comment]
Lets start with a simple guard of `if (config->metrics > 0)`
