### ISSUE TITLE
Add more internal metrics

### ISSUE THREAD

**Issue by An-DJ** [agroal/pgagroal#163]
**Is your feature request related to a problem? Please describe.**
The pgagroal lacks some metrics of internal resource state, such as network traffic and so on.

**Describe the solution you'd like**
This feature includes new metrics as follows:
- [X] `pgagroal_network_sent` which characterizes the network traffic sent
- [X] `pgagroal_network_received` which characterizes the network traffic received
- [X] `pgagroal_client_sockets` which characterizes the number of sockets client used
- [X] `pgagroal_self_sockets` which characterizes the number of sockets pgagroal used itself

**Comment by An-DJ** [comment]
@jesperpedersen I have pushed a new commit which contains the implementation of `pgagroal_client_sockets` and `pgagroal_self_sockets`. 

I am considering whether to remove metric `pgagroal_server_sockets`, since it is always equal to the total number of connections. Could you give me some advice?

**Comment by jesperpedersen** [comment]
`pgagroal_client_sockets` is the important one. `pgagroal_self_sockets` should stay more or less constant.

For `pgagroal_server_sockets` I would just use the existing metrics for connections, and display that as server - e.g. not a new metric.

**Comment by An-DJ** [comment]
> `pgagroal_client_sockets` is the important one. `pgagroal_self_sockets` should stay more or less constant.
> 
> For `pgagroal_server_sockets` I would just use the existing metrics for connections, and display that as server - e.g. not a new metric.

`Server sockets`  has been added into dashboard in new commit in #165. PTAL~ @jesperpedersen

**Comment by An-DJ** [comment]
@jesperpedersen Besides, I notice that the main memory size is fixed by configuration file like shared memory created by mmap and so on. I have no idea whether `pgagroal_mem_alloc` should be added into pgagroal. 

Could you give me some Suggestions?

**Comment by jesperpedersen** [comment]
There is a very minimal allocation rate which happens during startup of a connection, or with the client.

The pipeline uses a fixed buffer for communication so that doesn't change.

As such I don't think we need a metric for allocations, and there is no portable system function for checking memory usage.

**Comment by An-DJ** [comment]
> There is a very minimal allocation rate which happens during startup of a connection, or with the client.
> 
> The pipeline uses a fixed buffer for communication so that doesn't change.
> 
> As such I don't think we need a metric for allocations, and there is no portable system function for checking memory usage.

I think so, too. Thanks!
