### ISSUE TITLE
GSoC 2021 Summary: Metrics and monitoring

### ISSUE THREAD

**Issue by An-DJ** [agroal/pgagroal#170]
# Project
pgagroal: Metrics and monitoring

# Summary
This project aims to enhance the monitoring part which characterizes the current runtime status of pgagroal's pool, connections, clients, servers and internal resource usage. The dashboard as project outcomes can illustrate the key metrics and show clearly what DBA desires to know with pgagroal.

The main 2 parts are as follows:
* Organize more significant metrics which characterizes the current runtime status
* Create dashboards to better map trends in key metrics

# What is done
* 1443ddbfacbaf70e3b0854fabc6f5950a15d2a7f Add grafana dashboard to pgagroal
  * PR #152 
* 58907bcbd79b506b059d49dc6380ef2a9eddfc84 Split struct prometheus from struct configuration
  * Issue #153
  * PR #155 
* 44b7eb9561188e308a8258b6c225fc150668653c Add metrics of client `pgagroal_client_active`, `pgagroal_client_wait` and corresponding panels
  * Issue #158
  * PR #157
* 0b394f7dfd32d3f6eec8426101f3f0cde2eefbad Add new metric `pgagroal_wait_time` and corresponding panel
  * Issue #159
  * PR #160 
* f1bbe8a031ed20fb6f92a11adf78898b7d157730 Add new pool metric `pgagroal_query_count` and corresponding panel
  * Issue #159
  * PR #161
* b11de2bc8c77123fdcebc9b5f41123339c61513d Add new pool metric `pgagroal_tx_count` and corresponding panel
  * Issue #159
  * PR #162
* 816d412ab73a787176fdc8c69a8701013679746a Add internal network traffic metrics `pgagroal_network_sent`, `pgagroal_network_received` and corresponding panels
  * Issue #163
  * PR #164
* be953281992f77811f898ae4b55605571830811f Add internal socket metrics `pgagroal_client_sockets`, `pgagroal_self_sockets` and corresponding panels
  * Issue #163
  * PR #165
* 523e7bd3b0b23337ed1c9c3aa614fd90e229e72a Change Query rate and Transaction rate panels' unit `%` to `rps`
  * PR #166
* 436741ec89f96c33be2ad601fddd939bd246ca51 Add connections per database panel
  * PR #167
* d51e3e42b82ac8de123bcac9fb5d8ddeb4815142 Add new metric `pgagroal_pipeline_mode` and corresponding panel
  * PR #168
* d463bf3526d7bcd8a7a1cd63735d39ff1f53e8a2 Add new metric `pgagroal_connection_query_count` and new panel "Query rate per database"
  * PR #169
* 332658302eaf999bacfcbc28fbc937102193c2d3 Add additional description to metrics page and grafana dashboard
  * PR #171

# TODO
* Add metrics to describe the query time and transaction time
* Change appropriate total metrics to per-db or per-user statistics metrics

# References
* [Project home page](https://summerofcode.withgoogle.com/projects/#4640777642180608)
* [GSoC 2021 ideas:  (pgagroal: Metrics and monitoring)](https://wiki.postgresql.org/wiki/GSoC_2021#pgagroal:_Metrics_and_monitoring_.282021.29)
* [GSoC 2021 PostgreSQL Project Proposal (pgagroal: Metrics and monitoring) ](https://www.postgresql.org/message-id/attachment/121975/[GSoC]%20Metrics%20and%20Monitoring%20for%20pgagroal.pdf)
* [Related discussion](https://github.com/agroal/pgagroal/discussions/151)

**Comment by jesperpedersen** [comment]
Completed with a pass :partying_face:
