### ISSUE TITLE
log_connections and log_disconnections not documented

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#203]
According to <https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/configuration.c#L609> and <https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/configuration.c#L595> these settings are handled but not documented here <https://agroal.github.io/pgagroal/configuration.html>.
Are they hidden params and must not be handled?

**Comment by jesperpedersen** [comment]
Looks like they are in `doc/CONFIGURATION.md` but not on the web site.

**Comment by jesperpedersen** [comment]
Done in cd2988a022c73709e97a504197ea87469ed20851

Thanks !
