### ISSUE TITLE
log_level = debug is not undrstood

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#210]
In the configuration file, the `log_level` can be set to `debug1` but not to `debug`. While this is documented, I would expect and prefer to set `debug` instead of `debug1` that sounds more as a development setting. Also, in the case of `log_level = debug` the level is set to fallback `info` without any warning.

**Comment by jesperpedersen** [comment]
I would say `debug1`.

Anything at or above `info` should be necessary for the user to understand the pool operation.

**Comment by fluca1978** [comment]
Personally, I like the idea of `log_level = debug`. I've created a possible commit that allows for other debug level, even if not used at the moment.
Feel free to reject.
