### ISSUE TITLE
Option to cache Prometheus response

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#219]
Have an option that will cache a Prometheus response for `X` seconds

**Comment by fluca1978** [comment]
Just curious: do you mean avoid to send out the result of `metrics_page()` at every single request but to serve it as it was `x` seconds before?
Is such functon so heavy to serve that requires caching?
Could it be a static temporary file the solution? I mean write out `metrics_page()` to the file and serve such a file is still valid.

**Comment by jesperpedersen** [comment]
Prometheus requests are light-weight for pgagroal (and pgmoneta, but not for pgexporter).

I would just cache it as a `static` string, together with the last served timestamp.
