### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#221]
In the configuration page <https://github.com/agroal/pgagroal/blob/master/doc/CONFIGURATION.md> there is a link to a sample configuration to run pgagroal on localhost, the link should point to the `pgagroal.conf` configuration file, but the link is broken.

There is an extra `/pgagroal/` folder in the link.

**Comment by jesperpedersen** [comment]
Can you open a PR for it ?
