### ISSUE TITLE
prefill after switch-to

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#224]
Don't know if this is a valuable feature, but with `1.5` when I do a `switch-to` and/or a `reset-server` the prefill seems to be dropped.
I mean, when I start `pgagroal` the "initial" connections from `pgagroal_databases.conf` are established. When I do a `switch-to` to another server, the new server does not get the "initial" connection number but only the "minimum".
The same when I come back with another `switch-to` the original server.
Is there a reason or should `pgagroal` honor the "initial" connection every time a server is changed as primary?

**Comment by jesperpedersen** [comment]
I agree. `switch-to` should trigger prefill, since the connections on the previous primary should go into graceful

**Comment by jesperpedersen** [comment]
That is likely one way to do it

**Comment by fluca1978** [comment]
I could spend some time and effort on this, if you believe there are no other tricks and dangerous zones...

**Comment by jesperpedersen** [comment]
There is a bit more to it.

The old primary should never prefill no matter what the `min_size` is - in the case of `switch-to`.

**Comment by fluca1978** [comment]
> The old primary should never prefill no matter what the `min_size` is - in the case of `switch-to`.

I'm going to work on this starting from the next week, but in the meantime I'm reasoning about this.
When I switch-to a new server, the old primary will be graceful and the new one is going to get prefilled, and this is the problem I'm going to try to fix. If I then switch-to back to the old primary, why should I don't prefill it?

**Comment by jesperpedersen** [comment]
In relation to the `switch-to`.

`pgagroal_databases.conf`
```
mydb myuser 100 20 10
```
Initial
```
host1(20)(Primary)
host2(0)(Not init)
```
`switch-to(host2)`
```
host1(0)(Not init)
host2(20)(Primary)
```

`switch-to(host1)`
```
host1(20)(Primary)
host2(0)(Not init)
```

So, I think we agree, right ?

**Comment by fluca1978** [comment]
Yes, it was what I was thinking about.

**Comment by jesperpedersen** [comment]
:+1:
