### ISSUE TITLE
Issuing a reload with a single server makes the status Not Init

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#232]
Running pgagroal 7fa65ed55a2e75de29fb38070e68772947b46f01.
The configuration has a single server:
```
$ cat /etc/pgagroal/pgagroal.conf
...
[venkman]
host = venkman
port = 5432
primary = on
```

Once pgagroal has started the situation is:

```
$ pgagroal-cli details
Status:              Running
Active connections:  0
Total connections:   2
Max connections:     5
---------------------
Server:              venkman
Host:                venkman
Port:                5432
State:               Primary
---------------------
...
```

but then if issuing a reload the status of the *only* available server is lost:

```
$ pgagroal-cli reload && pgagroal-cli details
Status:              Running
Active connections:  0
Total connections:   2
Max connections:     5
---------------------
Server:              venkman
Host:                venkman
Port:                5432
State:               Not init
---------------------
...
```

No changes to the configuration.
This is related to #223 and in my opinion should be fixed before that issue.

**Comment by jesperpedersen** [comment]
We should probably have a `find_server` function that will loop through the existing servers, and find the `reload` definition.

In this precise case - we need to make sure that the atomic status flag is kept - if all the other information is the same.
