### ISSUE TITLE
Use a C macro to sleep?

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#263]
I think this could improve code readibility: there are several places (not many) where there is a code like fhis:

```
      else
      { 
      /* Sleep for 1ms */
        struct timespec ts; 
        ts.tv_sec = 0; 
        ts.tv_nsec = 1000000L; 
        nanosleep(&ts, NULL); 

       goto retry; 
      } 
```

such code performs a sleep and a jump, and is used when asking for a lock acquisition.
Cannot we wrap the code in a macro so that the above becomes:

```
      else
          SLEEP_AND_GOTO(1000000L,retry)
```

Could this improve source code readibility and avoid duplication of code?

**Comment by jesperpedersen** [comment]
Sure
