### ISSUE TITLE
Investigate [pgagroal] <defunct> processes

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#270]
Happens on `master` with d0d7c2b4c2926d4c4efd390a3909c1a14566b783.

**Comment by jesperpedersen** [comment]
This commit fixes the child-child process issue for prefill

**Comment by fluca1978** [comment]
Apparently this does not happen with only 348d6652dcbb321b61c50f1c5c1a69664e230c7a, so the single statement in the macro seems not related to me.

**Comment by fluca1978** [comment]
The problem effecively seems to were here <https://github.com/agroal/pgagroal/commit/348d6652dcbb321b61c50f1c5c1a69664e230c7a#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176L1075>, the process has already forked and so it was re-forking and prefilling.
Sorry for the problem.
