### ISSUE TITLE
Refactor `pgagroal-admin` commands

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#290]
Related to #253 and discussion in #289 (see <https://github.com/agroal/pgagroal/pull/289#issuecomment-1196884782>): `pgagroal-admin` could have a more consistent set of commands grouped by *command* and *subcommand*.
An example could be:  `user` and then `add` or `mod` or `del` In the previous example `user` is the command and the other three are the subcommands.

It should also provide a set of warning for deprecated commands only when `pgagroal` is greater than a specific version number,

**Comment by jesperpedersen** [comment]
:+1:
