### ISSUE TITLE
Make the version number comparable

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#292]
In `pgagroal.h` the version of the pooler is defined as a constant string:

```
#define VERSION "1.5.0"
```

this makes hard to compare version numbers within the program. I propose to split the version number into three numeric parts, providing an utility function to get the string-yfied version of the version number to display.

This is useful also to decide which part of code are deprecated or not depending on the version, as per discussion and needs in #289, #290, and #253.

**Comment by fluca1978** [comment]
Or even simpler, use a compile time macro to define both the version string and a numeric representation.

**Comment by jesperpedersen** [comment]
:+1:
