### ISSUE TITLE
use `calloc(3)` instead of `malloc(3)` & `memset(3)` ?

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#312]
Partially related to #190 , the source code is filled with memory allocations and zero filling like the following one:

```
ptr = malloc( ... );
memset( ptr, 0, ...);
```

wouldn't be possible to substitute this with `calloc(3)`? According to the documentation:

```
The calloc() function allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated  memory.        The  memory  is set to zero.
```

As an example, consider <https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/utils.c#L125>:

```
an = malloc(size);
memset(an, 0, size);
```

would become

```
an = calloc(1, size);
```

Another advantage, that should not happen in pgagroal, is that calloc detects size overflows (integer computation), while malloc does not.

**Comment by jesperpedersen** [comment]
Internally `calloc` checks for overflow as you said, so that is the main difference. Either way I would say, since we don't have `memset` in the `message` read/write path.
