### ISSUE TITLE
Segmentation Fault on transaction pipeline

### ISSUE THREAD

**Issue by vikingUnet** [agroal/pgagroal#343]
**Describe the bug**

Can't run pooler in transaction mode - get Segmentation Fault.

**To Reproduce**

```
/usr/local/bin/pgagroal -c /usr/local/etc/pgagroal/pgagroal.conf -a /usr/local/etc/pgagroal/pgagroal_hba.conf -u /usr/local/etc/pgagroal/pgagroal_users.conf
Segmentation fault
```

**Version**

1.6.0

**PostgreSQL**

13.5

**libev**

1:4.31-1

**OpenSSL**

1.1.1f-1ubuntu2.16

**Access method**

all (dfefault)

**OS**

20.04.1-Ubuntu

**ulimit**

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7584
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7584
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Configuration**

Can you provide the configuration pgagroal ?

* pgagroal.conf
```
[pgagroal]
host = *
port = 8432
failover = on
failover_script = /tmp/failover.sh

log_type = file
log_type = console
log_level = debug
log_path = /tmp/pgagroal.log
#log_connections = on
#log_disconnections = om

max_connections = 100
idle_timeout = 600
validation = off
unix_socket_dir = /tmp/

pipeline = transaction

[primary]
host = msherstyuk-master.spb.play.dc
port = 6001

[primary2]
host = 10.2.50.251
port = 6001
```
* pgagroal_hba.conf
```
#
# TYPE  DATABASE USER  ADDRESS  METHOD
#
host    all      all   all      all
```
* pgagroal_databases.conf
not used
* pgagroal_users.conf
```
[users]
tester "tester"
```
**Debug logs**

empty

**Tip**

Use \`\`\` before and after the text to keep the output as is.

**Comment by jesperpedersen** [comment]
If you add a pgagroal_databases.conf setup does your use-case work then ?

**Comment by vikingUnet** [comment]
> If you add a pgagroal_databases.conf setup does your use-case work then ?

Hello, [jesperpedersen](https://github.com/jesperpedersen)!

Unfortunately, there is no effect:
cat /usr/local/etc/pgagroal/pgagroal_databases.conf
```
#
# DATABASE USER    MAX_SIZE INITIAL_SIZE MIN_SIZE
#
tester     tester  all
```

Running command with additional pgagroal_databases config file:
```
m.sherstyuk@msherstyuk9:~$ /usr/local/bin/pgagroal -c /usr/local/etc/pgagroal/pgagroal.conf -a /usr/local/etc/pgagroal/pgagroal_hba.conf -u /usr/local/etc/pgagroal/pgagroal_users.conf -l /usr/local/etc/pgagroal/pgagroal_databases.conf
Segmentation fault
```

**Comment by jesperpedersen** [comment]
You should create `pgagroal_users.conf` with the `pgagroal-admin` tool.

https://github.com/agroal/pgagroal/blob/master/doc/tutorial/01_install.md#create-basic-configuration

**Comment by vikingUnet** [comment]
> You should create pgagroal_users.conf with the pgagroal-admin tool.
>
> https://github.com/agroal/pgagroal/blob/master/doc/tutorial/01_install.md#create-basic-configuration

Thanks for remark, i created pgagroal_users.conf  with command from pgagroal user:

```
pgagroal-admin -f usr/local/etc/pgagroal/pgagroal_users.conf -U tester -P tester add-user
```

And have pgagroal_databases.conf, but it is still Segmentation fault

**Comment by jesperpedersen** [comment]
Can you compile in Debug mode and run within gdb ?

Or what are your precise configuration ? I'm assuming that you are running the latest master or 1.5.x branch
