### ISSUE TITLE
Line number in structure limits but not in hba?

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#355]
While working on #239, I noted that the `struct limit` has a line number field <https://github.com/agroal/pgagroal/blob/master/src/include/pgagroal.h#L291> while other similar structures, most notably `struct hba` does not.
The line number is useful to report back errors in the configuration, e.g., <https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/configuration.c#L1303>.

In order to keep everything consistent, I would like to either remove the line number or to add it in similar structures, at leas in `struct hba`.

**Comment by jesperpedersen** [comment]
I think it would be good to have line numbers for all configuration files

**Comment by fluca1978** [comment]
> I think it would be good to have line numbers for all configuration files

Agree.
This means adding a `lineno` field in all structures, including `config`.

**Comment by jesperpedersen** [comment]
:+1:
