### ISSUE TITLE
Report inconsistent min_size/initial_size/max_size configurations

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#356]
In  <https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/configuration.c#L1228> the system tries to automagically adjust `max_size` and `min_size` depending on the value of `initial_size`.

This is not documented.

I suggest to report an error to the user when the configuration is wrong, not to adjust it to something the user could not have understood.
Therefore, report an error when:
- `max_size` < `MAX( min_size, intial_size )`
 - `min_size` > `MIN( max_size, initial_size )`
 - `initial_size` > `max_size` or `initial_size` < `min_size`
 - `max_size` < `min_size` or `min_size` > `max_size`
 - at least one the values is negative

**Comment by jesperpedersen** [comment]
:+1:
