### ISSUE TITLE
max_connection_age

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#361]
Create a `max_connection_age` setting that will define how long a connection will live - in seconds.

This configuration option will be checked once the connection is returned to the pool, or during the idle check.

Default is `-1` - e.g. not enabled.

**Comment by fluca1978** [comment]
What is the aim of killing a connection? I mean, isn't a way of augment latency, even if in favor of security?

If I get it right, the workflow should be:
- in `pgagroal_return_connection` check if `timestamp` is greater than `max_connection_age`
- if the above is true, `goto kill_connection` but probably there is something more to do in order to cleanup the connection

**Comment by jesperpedersen** [comment]
It is an option to remove a connection after a maximum amount of time.

So, it is `pgagroal_return_connection` - check - then `goto kill_connection` in that workflow

**Comment by 2010YOUY01** [comment]
I also want to make sure I get it right:
So the current implementation has a `timestamp` field inside `struct connection`, and an `idle_timeout` field inside `struct configuration`, they're used to make sure a connection won't stay in `STATE_FREE` (after returning back to the pool) longer
 than `idle_timeout`.
This `max_connection_age` is to make sure the time from a connection successfully get from `pgagroal_get_connection()` (turned into `STATE_INUSE`) to `pgagroal_return_connection()` or idle check/validation won't longer than this specified time period.

**Comment by jesperpedersen** [comment]
@2010YOUY01 Yes

**Comment by 2010YOUY01** [comment]
Awesome, may I work on this issue?

**Comment by fluca1978** [comment]
@2010YOUY01 if you work on this, there is a function in the configuration code, named `as_seconds` that can parse the parameter.
Remember to keep the parameter consisten across configuration reloads, see ``metrics_cache_max_age` for an hint.

**Comment by hao-tian-xu** [comment]
@2010YOUY01 Hi, I asked to find the issue to work on. Sorry for this..

**Comment by jesperpedersen** [comment]
This has been merged - thanks @hao-tian-xu !
