### ISSUE TITLE
Substitute other commands in pgagroal-cli

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#381]
This is not a problem, rather a possible improvement about command line consistency.
Now that we have new commands in `pgagroal-cli` and `pgagroal-admin`, and a way to mark a command deprecated, I propose to apply the following minor changes in `pgagroal-cli`:
- deprecate `is-alive` in favor of either `check` or `ping`
- deprecate `details` in favor of either `status details` or `status --verbose`

**Comment by jesperpedersen** [comment]
I would say `ping` and `status details`
