### ISSUE TITLE
Add a command to `pgagroal-cli` get configuration file locations

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#388]
I propose to add a command to `pgagroal-cli` to get information about the configuration files used by the deamon.
My proposal is to add `conf ls` (or `conf files`), so that for instance:

```
$ pgagroal-cli conf ls
Configuration file:        /etc/pgagroal/pgagroal.conf
HBA file:                  /etc/pgagroal/pgagroal_hba.conf
Limit file:                /etc/pgagroal/pgagroal_databases.conf
Frontend users file:       /etc/pgagroal/pgagroal_users.conf
Admins file:               /etc/pgagroal/pgagroal_frontend_users.conf
Superuser file:            /etc/pgagroal/pgagroal_admins.conf
```

In this way, even remotely, it is possible to know where the configuration files are located on the system running `pgagroal`.

**Comment by jesperpedersen** [comment]
I'm ok with this - so :+1:
