### ISSUE TITLE
Fix separation of concerns in code for `conf set` and `conf get` of `pgagroal-cli`

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#390]
In `pgagroal-cli` the commands `conf set` and `conf get` have the output printing interleaved with the "cli" code.
See for example <https://github.com/agroal/pgagroal/blob/master/src/cli.c#L957> and <https://github.com/agroal/pgagroal/blob/master/src/cli.c#L878>.
This is not symmetric with all the other command implementations and makes more difficult to refactor the code when having to deal with commands output (e.g., #385 ).
The commands should be implemented as the others, so the printing part has to be placed into the `pgagroal_read_xxx` methods in the management code.

**Comment by jesperpedersen** [comment]
I think we should look into have all output separated from `management.c` so putting the necessary information into output parameters...
