### ISSUE TITLE
Fix error message in `pgagroal-admin master-key`

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#428]
There is a wrong error message reporting `pgexporter`.

See #425

**Comment by fluca1978** [comment]
My idea about the check for the `master-key` was a little different: do we care if the master key file is in place? We should care about the existance of any of the "users.conf" files, and warn the user about that.

**Comment by jesperpedersen** [comment]
I think that is more a documentation issue... if a user want to change master key they should know that all the user based files need to changed as well
