### ISSUE TITLE
Documentation framework

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#441]
It can be ported from https://github.com/pgmoneta/pgmoneta

**Comment by decarv** [comment]
What is the idea here? Does this refer to pgmoneta's user guide and developer guide? Should we keep both discussions here or maybe open two new issues (or two discussions under Discussions tab)?

**Comment by jesperpedersen** [comment]
I think we found a good setup in pgmoneta, so the functionality can be ported over.

And, it would be a user and a developer guide for pgagroal
