### ISSUE TITLE
Management protocol documentation

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#446]
Related to #441 and the work done in #392 , there is the need to document the management protocol.
Adding a `MANAGEMENT.md` file could be ideal, and link it in the development documentation.

**Comment by fluca1978** [comment]
@EuGig would you like to work on this?

**Comment by EuGig** [comment]
Sure!

**Comment by jesperpedersen** [comment]
Closing this since #466 will simplify the management protocol
