### ISSUE TITLE
Replace cJSON with in-tree implementation

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#465]

**Comment by jesperpedersen** [comment]
@MohanadKh03 Do you want to take this one ?

You can see how to use the in-tree JSON API in the https://github.com/pgmoneta/pgmoneta project

**Comment by MohanadKh03** [comment]
Sure
Just to make sure I understand this though, everything that uses cJSON API should instead use the native in-tree parser API like how pgmoneta does. Right ?

**Comment by jesperpedersen** [comment]
Correct, so you search for all usage of cJSON and replace it
