### ISSUE TITLE
Remove deprecated CLI commands

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#467]

**Comment by MohanadKh03** [comment]
Is this available to work on ? 
I have ran through the codebase and found out that the deprecated commands can be removed from the ```command_table``` without having any effect on the command parser

Obviously it should be added in the documentations as well that the deprecated commands have been replaced and not used at all starting the current release version (not sure if it will be released in 2.0.0 or not ?) and not used anymore

So is this how it should be done or there are more details that I am missing about this ?

**Comment by jesperpedersen** [comment]
No, you can just remove everything - code and documentation.

Remember to add yourself to `AUTHORS`
