### ISSUE TITLE
libev option ?

### ISSUE THREAD

**Issue by hellower** [agroal/pgagroal#62]
libev option =>  Valid options: auto, select, poll, epoll, linuxaio, iouring, devpoll and port

Of these options, is epoll the best for Linux?
otherwise,
auto / select / epoll
Which value do you recommend?

**Comment by jesperpedersen** [comment]
Yes, until `iouring` becomes available (Linux 5.6.1+).

`auto` should always find the fastest solution.

Hope this helps !

**Comment by hellower** [comment]
Thank you!
