### ISSUE TITLE
pgagroal reconnection on postgresql  restart 

### ISSUE THREAD

**Issue by hellower** [agroal/pgagroal#63]
I .-------------------------------------  configuration --------------------------------------
__STAGE__# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# ls
pgagroal.conf  pgagroal_databases.conf  pgagroal_hba.conf  pgagroal_users.conf  start.sh*
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# cat pgagroal.conf 
[pgagroal]
host = localhost
port = 9091

log_type = console
log_level = info
#log_path =  /tmp/pgagroal.log

max_connections = 1000
idle_timeout = 600
validation =  off
unix_socket_dir = /tmp/.s.pgagroal

log_connections = true
log_disconnections = true

[primary]
host = localhost
port = 9081
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# cat pgagroal_databases.conf 
\#
\# DATABASE USER  MAX_CONNECTIONS INITIAL_SIZE
\#
\#all        all   all
tarantula tarantula 200 10
tarantula kong        5  3
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# cat pgagroal_hba.conf 
\#
\# TYPE  DATABASE USER  ADDRESS  METHOD
\#
host    all      all   all      all
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# cat pgagroal_users.conf 
tarantula:blabla.......................
kong:blabla.......................
[root@ssdnodes00:/tmp/pgagroal]
__STAGE__# cat start.sh 
 pgagroal -c pgagroal.conf  -a pgagroal_hba.conf -l pgagroal_databases.conf -u pgagroal_users.conf
[root@ssdnodes00:/tmp/pgagroal]

II. ------------------ postgresql restart ------------
pg_ctl restart -w -c 

III. ------------------- connection test ---------------------
__STAGE__$ psql -U tarantula -d tarantula -h localhost -p 9091  (<====pgagroal port)
 
psql: error: could not connect to server: FATAL:  connection pool is full   ????
[postgres@ssdnodes00:/home/postgres]

VI. \------------------------------------ only session count : 10 ------------------
postgres@[local]:9081:postgres(15:09:35)
SQL> select count(*) from pg_stat_activity;
 count 
-------
    10
(1 row)
-
\------------------------------------------------------------------------

Upon restart of postgresql, Shoul I  restart pgagroal deamon ???

**Comment by jesperpedersen** [comment]
If PostgreSQL will restart you need to run

```
validation = foreground
```

to make sure that a connection is valid when obtained.

However, there are some issues (#64) with `validation = off` in this scenario, so make sure to update either `master` or `0.5.x`.

Hope this helps.

**Comment by hellower** [comment]
Thank you!
