### ISSUE TITLE
initialization size ?

### ISSUE THREAD

**Issue by hellower** [agroal/pgagroal#66]
[postgres@b3263acce0ca bin]$ cat pgagroal_databases.conf 
# DATABASE USER  MAX_CONNECTIONS **INITIAL_SIZE**
#
#all        all   all
tarantula tarantula 200 **_10_**
tarantula kong        5  **_3_**

========================================================

postgres=# select count(*),usename from pg_stat_activity group by usename;
 count |  usename  
-------+-----------
     4 | 
    **_10 | tarantula_**
     2 | postgres
     **_3 | kong_**
(4 rows)

...................after pg_restart ............

postgres=# select count(*),usename from pg_stat_activity group by usename;
 count |  usename  
-------+-----------
     4 | 
     **_1 | tarantula_**
     2 | postgres
(3 rows)

After  postgresql restart, 
The initialization value is ignored, is it expected behavior?

**Comment by jesperpedersen** [comment]
Yeah, I thought about that when doing the work for #65, so I have added #67 for this.

Then you can do

```
tarantula tarantula 200 10 10
```

if you always want 10 active connections.

**Comment by jesperpedersen** [comment]
This should be done now.
