### ISSUE TITLE
Enable hardening features during the normal build if the compiler supports it

### ISSUE THREAD

**Issue by darix** [agroal/pgagroal#73]
- PIE
- relro

I am sure your security would be happy to have that out of the box.

**Comment by jesperpedersen** [comment]
The Release build will now apply

```
-Wformat
-Wformat-security
-fstack-protector-strong or -fstack-protector
-fPIC
-fPIE -pie
-Wl,-z,relro
-Wl,-z,now
```
if supported in addition to `-O2 -DNDEBUG`.

Thank you for your feedback !

**Comment by darix** [comment]
Could you also turn it on for CMAKE_BUILD_TYPE:STRING=RelWithDebInfo ?

I am kinda sure your rpm build will use the same build type

**Comment by darix** [comment]
after patching it locally I run into

```
[    4s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld:
/tmp/libpgagroal.so.0.7.0.E0uhVm.ltrans0.ltrans.o:
relocation R_X86_64_PC32 against symbol `_zf_log_tag_prefix' can not be used when making a shared object; recompile with -fPIC
```

So not all objects are built with -fPIC

**Comment by jesperpedersen** [comment]
Ok, thanks -- I'll look into this

**Comment by darix** [comment]
it works on 15.2 but fails on Tumbleweed. will poke my GCC guys.

**Comment by jesperpedersen** [comment]
Ok, let me know

**Comment by darix** [comment]
in any case ... the patch is not quite correct either e.g. -pie is a linker flag you dont need to pass it in via CFLAGS
