### ISSUE TITLE
Max connection could see only 8 even max_connection parameter set to 100

### ISSUE THREAD

**Issue by vasudba** [agroal/pgagroal#98]
Status:              Running
Active connections:  0
Total connections:   0
Max connections:     8
---------------------
Server:              primary
Host:                localhost
Port:                5432
State:               Not init
---------------------
Connection    0:     Not initialized
Connection    1:     Not initialized
Connection    2:     Not initialized
Connection    3:     Not initialized
Connection    4:     Not initialized
Connection    5:     Not initialized
Connection    6:     Not initialized
Connection    7:     Not initialized

We could see max connections 8 only even after max_connections parameter set to 100.

**Comment by jesperpedersen** [comment]
You need to compile in `Release` mode - `Debug` has a max of 8 connections

**Comment by vasudba** [comment]
Thank you, complied release mode, now connection max_connections showing as per parameter.
